ARG BASE_IMAGE="localhost/workstation:rechunked"

FROM ${BASE_IMAGE}

COPY versions/workstation/kmod.sh /tmp/kmod.sh
COPY files/ /

RUN --mount=type=secret,id=mok_priv_b64 \
    MOK_PRIV_B64="$(cat /run/secrets/mok_priv_b64 2>/dev/null || echo '')" /tmp/kmod.sh

RUN set -xe; kver=$(ls /usr/lib/modules); env DRACUT_NO_XATTR=1 dracut -vf /usr/lib/modules/$kver/initramfs.img "$kver"
RUN rm -rf /tmp/*
RUN bootc container lint
